Z=[I] {F} .
I = "#include<" L {L} ".h>" .

F = R L {L} "(" R ")" B .
B = "{" {C} "}" .
C = (P | V) ";" .
P = ( "printf(" T ")" ) | ( "scanf(" T ")" ) | ( R {L}) | ( "if(" {L} ")" (P | B)).
T = S {U} .
U = "," ({L} | S) .
V = L {L} "=" L {L} .
R = "void" | "int" | "char" .
L = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "\n" | "%" | "+" | "-" | "*" | "/" | "&" | "[" | "]" | "8" | "0" .
S = """ {L} """ .
$
Z
